services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command: serve
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "80"
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ntfy_data:/etc/ntfy
    restart: unless-stopped
    labels:
      yantr.app: "ntfy"
      yantr.service: "Notification Server"

volumes:
  ntfy_cache:
  ntfy_data:
