services:
  web:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie-web
    restart: unless-stopped
    labels:
      yantr.app: "mealie"
      yantr.service: "Web UI"
    ports:
      - "9000"
    environment:
      TZ: ${TZ:-UTC}
      ALLOW_SIGNUP: "true"
      DB_ENGINE: sqlite
    volumes:
      - mealie_data:/app/data

volumes:
  mealie_data:
