services:
  web:
    image: octoprint/octoprint:latest
    container_name: octoprint
    labels:
      yantr.app: "octoprint"
      yantr.service: "Web UI"
    privileged: true
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "5000"
    volumes:
      - octoprint_data:/octoprint
    restart: unless-stopped

volumes:
  octoprint_data:
