services:
  server:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web-server
    restart: unless-stopped
    labels:
      yantr.app: "calibre-web"
      yantr.service: "Web UI"
    ports:
      - "8083"
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - calibre_web_config:/config
      - calibre_web_books:/books

volumes:
  calibre_web_config:
  calibre_web_books:
