services:
  web:
    image: tombursch/kitchenowl:latest
    container_name: kitchenowl-web
    labels:
      yantr.app: kitchenowl
      yantr.service: Web UI
    environment:
      TZ: ${TZ:-UTC}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_DRIVER: postgresql
      DB_HOST: kitchenowl-db
      DB_NAME: kitchenowl
      DB_USER: kitchenowl
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080"
    volumes:
      - kitchenowl_files:/data
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:latest
    container_name: kitchenowl-db
    environment:
      POSTGRES_DB: kitchenowl
      POSTGRES_USER: kitchenowl
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - kitchenowl_db:/var/lib/postgresql/data
    restart: unless-stopped
    labels:
      yantr.app: kitchenowl
      yantr.service: db
volumes:
  kitchenowl_files: null
  kitchenowl_db: null
