services:
  netbird:
    image: netbirdio/netbird:latest
    container_name: netbird
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    network_mode: host
    environment:
      NB_MANAGEMENT_URL: ${NB_MANAGEMENT_URL:-https://api.wiretrustee.com:443}
      NB_ADMIN_URL: ${NB_ADMIN_URL:-https://app.netbird.io:443}
      NB_SETUP_KEY: ${NB_SETUP_KEY}
      TZ: ${TZ:-UTC}
    volumes:
      - netbird_config:/etc/netbird
    restart: unless-stopped
    labels:
      yantr.app: "netbird"
      yantr.service: "VPN Client"

volumes:
  netbird_config:
