services:
  web:
    image: ghcr.io/9001/copyparty-ac:latest
    container_name: copyparty
    labels:
      yantr.app: "copyparty"
      yantr.service: "Web UI"
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "3923"
    volumes:
      - copyparty_config:/cfg/hists
      - copyparty_shared:/shr
      - copyparty_media:/media
      - copyparty_uploads:/uploads

volumes:
  copyparty_config:
  copyparty_shared:
  copyparty_media:
  copyparty_uploads:
