services:
  pyramid:
    image: ghcr.io/fiatjaf/pyramid:latest
    restart: unless-stopped
    ports:
      - "3334"
    volumes:
      - data:/app/data
    labels:
      yantr.app: pyramid
      yantr.service.3334: Web UI, WebSocket Endpoint, Blossom Endpoint
      yantr.port.3334: HTTP
volumes:
  data: {}
x-yantr:
  name: pyramid
  tags:
    - nostr
    - relay
    - blossom
    - community
    - git
  short_description: a wondrous furnace of communityzenship backed by a dynamic
    ladder of socialhood
  description: pyramid is a Nostr service suite for small community or personal
    relays. It includes a Nostr relay, Blossom file server, NIP-29 chat rooms,
    and GRASP Git hosting. Invite friends to your relay and control how many
    users they can further invite.
  usecases:
    - Small-scale community Nostr relay for yourself and friends
    - Group chats for your friends or the public
    - Host files such as media in Nostr posts or website files for nsites
    - Host Git repositories using the GRASP protocol
  website: https://github.com/fiatjaf/pyramid
  logo: QmWhbSnNbgBASZSX42RDfgUkZb6gKytRJyV3yRbr3YzYxr
  notes:
    - Public access is required for full function (use reverse proxy or
      Cloudflare Tunnel)
    - Depending on the popularity of your Nostr profile you may see high traffic
      on your ISP plan
