services:
  web:
    image: stonith404/pingvin-share:latest
    container_name: pingvin-share
    labels:
      yantr.app: "pingvin-share"
      yantr.service: "Web UI"
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "3000"
    volumes:
      - pingvin_share_backend:/opt/app/backend/data
      - pingvin_share_images:/opt/app/frontend/public/img

volumes:
  pingvin_share_backend:
  pingvin_share_images:
