services:
  bambustudio:
    image: lscr.io/linuxserver/bambustudio:latest
    container_name: bambustudio
    volumes:
      - bambustudio-data:/config
    ports:
      - "3000"
      - "3001"
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      yantr.app: "bambustudio"
      yantr.service: "Bambu Studio"

volumes:
  bambustudio-data:
    name: bambustudio-data
