services:
  linux-box:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: linux-box
    labels:
      yantr.app: "linux-box"
      yantr.service: "SSH Server"
    environment:
      USER_NAME: ${SSH_USER}
      USER_PASSWORD: ${SSH_PASSWORD}
      PASSWORD_ACCESS: "true"
      SUDO_ACCESS: "true"
    ports:
      - "2222"
    restart: unless-stopped

