services:
  web:
    image: ghcr.io/blakeblackshear/frigate:latest
    container_name: frigate
    labels:
      yantr.app: "frigate"
      yantr.service: "Web UI"
    privileged: true
    shm_size: "128mb"
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "8971"
      - "5000"
      - "8554"
    volumes:
      - frigate_config:/config
      - frigate_media:/media/frigate
    restart: unless-stopped

volumes:
  frigate_config:
  frigate_media:
