services:
  sikka:
    image: besoeasy/sikka:latest
    container_name: sikka
    restart: unless-stopped
    labels:
      yantr.app: "sikka"
      yantr.service: "Node API and Wallet"
    environment:
      nodeprivatekey: ${nodeprivatekey:-}
      nodeaddress: ${nodeaddress:-}
      nodemessage: ${nodemessage:-}
    ports:
      - "8080"
    volumes:
      - sikka-data:/home/sikka/data

volumes:
  sikka-data:
