services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    container_name: lubelogger-app
    labels:
      yantr.app: "lubelogger"
      yantr.service: "Web UI"
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "8080"
    volumes:
      - lubelogger_config:/App/config
      - lubelogger_data:/App/data
      - lubelogger_documents:/App/wwwroot/documents
      - lubelogger_images:/App/wwwroot/images
      - lubelogger_translations:/App/wwwroot/translations
      - lubelogger_log:/App/log
    restart: unless-stopped

volumes:
  lubelogger_config:
  lubelogger_data:
  lubelogger_documents:
  lubelogger_images:
  lubelogger_translations:
  lubelogger_log:
