services:
  pcsx2:
    image: lscr.io/linuxserver/pcsx2:latest
    container_name: pcsx2
    volumes:
      - pcsx2-data:/config
    ports:
      - "3000"
      - "3001"
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      yantr.app: "pcsx2"
      yantr.service: "PCSX2"

volumes:
  pcsx2-data:
    name: pcsx2-data
