x-yantr:
  name: Just. Download.
  tags: [ media, torrent, download, p2p, utility ]
  short_description: Simple torrent downloader that bridges Torznab indexers with Transmission.
  description: Simple torrent downloader that bridges Torznab indexers with
    Transmission. Just. Download. is a self-hosted application focused on media,
    torrent, download, p2p. It can be deployed on any device via Docker Compose.
  usecases:
    [
      Self-host Just. Download. on your home server to simple torrent
        downloader that bridges torznab indexers with transmission without
        depending on third-party cloud services.,
      "Use Just. Download. to manage your media workflows privately, keeping
        all data under your control on local infrastructure."
    ]
  website: https://codeberg.org/highghlow/just-download

services:
  just-download:
    image: codeberg.org/highghlow/just-download:v1.0.9
    container_name: just-download
    labels:
      yantr.app: just-download
      yantr.service.5000: Web UI
      yantr.port.5000: HTTP
    ports:
      - "5000"
    volumes:
      - just-download_config:/config
    environment:
      LOCK_TRANSMISSION_CONFIG: 1
      CONFIG_LOCATION: /config/config.json
      CONFIG: '{"indexers": [], "transmission": {"host": "transmission_server_1",
        "port": 9091}}'
    restart: unless-stopped

volumes:
  just-download_config: null
