services:
  tor:
    image: containers.torproject.org/tpo/onion-services/onimages/tor:alpine
    container_name: cashu-me-tor
    labels:
      yantr.app: "cashu-me"
      yantr.service: "Tor Onion Service"
    restart: unless-stopped
    volumes:
      - tor-keys:/var/lib/tor
    environment:
      - TOR_ORPORT_PORT=0
      - TOR_CONTROL_PORT=9051
      - TOR_DNS_PORT=53
    command: |
      SOCKSPort 0.0.0.0:9050
      HiddenServiceDir /var/lib/tor/onion_service
      HiddenServicePort 80 127.0.0.1:3000

  web:
    build:
      context: https://github.com/cashubtc/cashu.me.git#main
      dockerfile: Dockerfile
    container_name: cashu-me
    labels:
      yantr.app: "cashu-me"
      yantr.service: "Web UI"
    restart: unless-stopped
    ports:
      - "3000"

volumes:
  tor-keys:
