services:
  linux-box:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linux-box
    hostname: linux-box
    restart: unless-stopped
    labels:
      yantr.app: "debian"
      yantr.service: "Linux Box"
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    ports:
      - "22"
    volumes:
      - debian-home:/home

volumes:
  debian-home:
    name: debian-home
