services:
  app:
    image: ghcr.io/egzola/bitbalance:1.0.18
    restart: unless-stopped
    ports:
      - "3710"
    volumes:
      - bitbalance-data:/data
    environment:
      PORT: "3710"
      ELECTRUM_HOST: ${ELECTRUM_HOST:-"fulcrum.sethforprivacy.com"}
      ELECTRUM_PORT: ${ELECTRUM_PORT:-50001}
    labels:
      yantr.app: "bitbalance"
      yantr.service: "Web UI"

volumes:
  bitbalance-data:
