x-yantr:
  name: PhotoPrism
  tags: [ photos, gallery, ai, media, self-hosted ]
  short_description: AI-Powered Photos App for organizing and sharing your
    collection on the Decentralized Web.
  description: PhotoPrism is an AI-powered app for browsing, organizing, and
    sharing your photo collection. It makes use of the latest technologies to
    tag and find pictures automatically without getting in your way. Say goodbye
    to the endless scrolling and let PhotoPrism's AI find the best shots.
  usecases:
    [
      Organize personal photo collections.,
      Automatically tag photos using AI.,
      Share albums with friends and family.
    ]
  website: https://photoprism.app/
  env_generators:
    PHOTOPRISM_ADMIN_PASSWORD:
      length: 16
      charset: alnum
    PHOTOPRISM_DATABASE_PASSWORD:
      length: 24
      charset: alnum
    MARIADB_ROOT_PASSWORD:
      length: 32
      charset: alnum

services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    labels:
      yantr.app: photoprism
      yantr.service.2342: Web UI
      yantr.port.2342: HTTP
    ports:
      - "2342"
    environment:
      PHOTOPRISM_ADMIN_USER: ${PHOTOPRISM_ADMIN_USER:-admin}
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_AUTH_MODE: password
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: mariadb:3306
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_DATABASE_USER: photoprism
      PHOTOPRISM_DATABASE_PASSWORD: ${PHOTOPRISM_DATABASE_PASSWORD}
    volumes:
      - photoprism_originals:/photoprism/originals
      - photoprism_storage:/photoprism/storage
    restart: unless-stopped
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:11
    container_name: photoprism-db
    labels:
      yantr.app: photoprism
      yantr.service.2342: Web UI
      yantr.port.2342: HTTP
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDAEMON_BUG_WORKAROUND: "1"
      MARIADB_DATABASE: photoprism
      MARIADB_USER: photoprism
      MARIADB_PASSWORD: ${PHOTOPRISM_DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - photoprism_db:/var/lib/mysql
    restart: unless-stopped

volumes:
  photoprism_originals: null
  photoprism_storage: null
  photoprism_db: null
